version: "3.7"

services:
  db:
    image: postgres:11.4
    ports: 
      - 5432:5432
    hostname: postgres
    environment:
      POSTGRES_DB: spa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
     - postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: spa-serverless
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "./scripts/start-win.sh && ls"
    network_mode: host
    depends_on:
      - db

volumes:
  postgres:
  .volumes: